"""charging sessions

Revision ID: b5ed58681c2c
Revises: 189f3d49c703
Create Date: 2026-10-04 21:29:35.340881
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b5ed58681c2c'
down_revision: str | None = '189f3d49c703'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_sessions',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('outlet_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='session_status'), nullable=False),
    sa.Column('end_reason', sa.Enum('TIME_EXPIRED', 'USER_ENDED', 'ENERGY_CAP', 'POWER_CAP', 'IDLE_TIMEOUT', 'FAULT', 'OPERATOR_ENDED', name='session_end_reason'), nullable=True),
    sa.Column('energy_wh', sa.Integer(), nullable=False),
    sa.Column('power_w', sa.Integer(), nullable=True),
    sa.Column('cost_kobo', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charging_sessions_booking_id'), 'charging_sessions', ['booking_id'], unique=True)
    op.create_index(op.f('ix_charging_sessions_outlet_id'), 'charging_sessions', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_charging_sessions_status'), 'charging_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charging_sessions_status'), table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_outlet_id'), table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_booking_id'), table_name='charging_sessions')
    op.drop_table('charging_sessions')
    # ### end Alembic commands ###
